name: Caller Workflow Using Actions


on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v3.4.0
      - uses: /.github/actions/My Called Action@main
