name: Workflow2

on:
 workflow_run:
    workflows: [Workflow1]
    types: [completed]
    branches: [claravilla-patch-1]
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-20.04
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  steps:
   - run: echo "This works"
 non-build:
  runs-on: ubuntu-20.04
  if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  steps:
   - run: echo "this failed"
 
