name: Run on push
on:
 pull_request:
   types: [opened]

jobs:
 diff:
  runs-on: ubuntu-latest
  steps:
    - run: echo this is my first diff
    - run: sleep 3m
 print-end:
  runs-on: ubuntu-latest
  needs: [diff]
  steps:
    - run: echo this is the end of the first job
