name: Test input

on:
  workflow_dispatch:
    inputs:
      countries:
        description: "List of countries to deploy secrets for. The input should be a comma separated string e.g. 'AU,DE'"
        required: false
        type: string

jobs:
  printInput:
   runs-on: ubuntu-20.04
   matrix:
    strategy:
       country: IFS="," read -ra ADDR<<<"${{github.event.inputs.countries}}"
   steps:
   - name: printInput
     run : echo ${{ github.event.inputs.countries }}
  #  - name: split input
  #    id: split
  #    run: |
  #      array=IFS="," read -ra ADDR<<<"${{github.event.inputs.countries}}"
  #      echo array >> $GITHUB_OUTPUT
     
   - name: print split value
     run: echo ${{ matrix.country}}
