name: Test input

on:
  workflow_dispatch:
    inputs:
      countries:
        description: "List of countries to deploy secrets for. The input should be a comma separated string e.g. 'AU,DE'"
        required: false
        type: string
env:
 VAR: 'this works' 
 PAYPAL_CLIENT_SECRET_DE: 'DE secret'
 PAYPAL_CLIENT_SECRET_AU: 'AU secret'

jobs:
  printInput:
   runs-on: ubuntu-20.04
   strategy:
    matrix: 
       country: ${{ fromJSON(github.event.inputs.countries) }}
   steps:
   - name: printInput
     run : echo ${{ matrix.country }}
   - name: print Env Var
     run: echo ${{ env.VAR }}
   - name: testFormat
     run: echo ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
   - name: print Format
     run: echo ${{ format('{0}', env.VAR) }}
   - name: print Both
     run: echo ${{ matrix.country}}_${{ format('{0}', env.VAR) }}
   - name: test PP client
     run: echo PAYPAL_CLIENT_ID_${{ matrix.country }}
   - name: test PP env works
     run: echo ${{ env.PAYPAL_CLIENT_SECRET_AU }}
   - name: test PP with format
     run: echo PAYPAL_CLIENT_SECRET_${{format('{0}', matrix.country)}}
   - name: test PP expression
     run:  echo ${{ env.PAYPAL_CLIENT_SECRET_[format('{0}', matrix.country)]}}
