name: Test input

on:
  workflow_dispatch:
    inputs:
      countries:
        description: "List of countries to deploy secrets for. The input should be a comma separated string e.g. 'AU,DE'"
        required: false
        type: string
env:
 VAR: 'this works' 

jobs:
  printInput:
   runs-on: ubuntu-20.04
   strategy:
    matrix: 
       country: ${{ fromJSON(github.event.inputs.countries) }}
   steps:
   - name: printInput
     run : echo ${{ matrix.country }}
   - name: print Env Var
     run: echo ${{ env.VAR }}
   - name: testFormat
     run: echo ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
   - name: print Format
     run: echo ${{ format('{0}', env.VAR) }}
#    - name: print Both
#      run: echo ${{ matrix.country}} bla ${{ [format('{0}', env.VAR)] }}
