name: Test input

on:
  workflow_dispatch:
    inputs:
      countries:
        description: "List of countries to deploy secrets for. The input should be a comma separated string e.g. 'AU,DE'"
        required: false
        type: string

jobs:
  printInput:
   runs-on: ubuntu-20.04
   steps:
   - name: printInput
     run : echo ${{ github.event.inputs.countries }}
   - name: split input
     id: split
     run: echo IFS="," read -ra ADDR<<<"${{github.event.inputs.countries}}" >> $GITHUB_OUTPUT
   
   - name: print split value
     run: echo {{steps.split.outputs}}
