name: triggered-on-workflow1-exit-action-on-failure

on:
 workflow_run:
    workflows: [Workflow 1]
    types: [completed]
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-20.04
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  steps:
   - run: echo "This works"
 non-build:
  runs-on: ubuntu-20.04
  if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  steps:
   - run: exit 1
 
